export const PROCESS_ACTION_START = 'PROCESS_ACTION_START';
export const PROCESS_ACTION_COMPLETED = 'PROCESS_ACTION_COMPLETED';
export const PROCESS_ACTION_ERROR = 'PROCESS_ACTION_ERROR';
export const LOCK_TOURNAMENT_ACTION = 'LOCK_TOURNAMENT_ACTION';
export const UNLOCK_TOURNAMENT_ACTION = 'UNLOCK_TOURNAMENT_ACTION';
export const ADD_NOTICE_ACTION = 'ADD_NOTICE_ACTION';
export const CALCULATE_POINTS_ACTION = 'CALCULATE_POINTS_ACTION';
export const CALCULATE_RANKING_ACTION = 'CALCULATE_RANKING_ACTION';
