export const GET_RANDOM_NUMBER = 'GET_RANDOM_NUMBER';
export const GET_RANDOM_NUMBER_PENDING = 'GET_RANDOM_NUMBER_PENDING';
export const GET_RANDOM_NUMBER_REJECTED = 'GET_RANDOM_NUMBER_REJECTED';
export const GET_RANDOM_NUMBER_COMPLETE = 'GET_RANDOM_NUMBER_COMPLETE';
