export const ACTION_START = 'ACTION_START';
export const ACTION_COMPLETED = 'ACTION_COMPLETED';
export const GET_MATCH_LIST = 'GET_MATCH_LIST';
export const GET_MATCH_LIST_ERROR = 'GET_MATCH_LIST_ERROR';
export const CREATE_MATCH = 'CREATE_MATCH';
export const CREATE_MATCH_ERROR = 'CREATE_MATCH_ERROR';
export const ACTION_ERROR = 'ACTION_ERROR';
