export const LOGGED_IN_USER = 'LOGGED_IN_USER';
export const LOGGED_OUT_USER = 'LOGGED_OUT_USER';
export const START_LOGGED_IN_USER = 'START_LOGGED_IN_USER';
export const LOGGED_IN_USER_SUCCESS = 'LOGGED_IN_USER_SUCCESS';
export const LOGGED_IN_USER_FAILURE = 'LOGGED_IN_USER_FAILURE';
