export const FETCH_ACCOUNT_BILL = 'FETCH_ACCOUNT_BILL';
export const FETCH_ACCOUNT_BILL_STARTED = 'FETCH_ACCOUNT_BILL_STARTED';
export const FETCH_ACCOUNT_BILL_COMPLETED = 'FETCH_ACCOUNT_BILL_COMPLETED';
export const FETCH_ACCOUNT_BILL_ERROR = 'FETCH_ACCOUNT_BILL_ERROR';
export const FETCH_ACCOUNT_BILL_CLEAR = 'FETCH_ACCOUNT_BILL_CLEAR';
