export const ACTION_START = 'HOME_ACTION_START';
export const ACTION_ERROR = 'HOME_ACTION_ERROR';
export const GET_UPCOMING_MATCHES_LIST = 'GET_UPCOMING_MATCHES_LIST';
export const GET_MOST_PICKED_PLAYER_LIST = 'GET_MOST_PICKED_PLAYER_LIST';
export const GET_TOP_PERFORMING_PLAYER_LIST = 'GET_TOP_PERFORMING_PLAYER_LIST';
export const GET_MOST_SCORING_USER_LIST = 'GET_MOST_SCORING_USER_LIST';
