export const ACTION_START = 'STATS_ACTION_START';
export const ACTION_ERROR = 'STATS_ACTION_ERROR';
export const FETCH_PLAYER_STATS = 'FETCH_PLAYER_STATS';
export const FETCH_USER_STATS = 'FETCH_USER_STATS';
export const FETCH_MATCH_STATS = 'FETCH_MATCH_STATS';
