export const ACTION_START = 'ACTION_START';
export const ACTION_COMPLETED = 'ACTION_COMPLETED';
export const GET_VENUE_LIST = 'GET_VENUE_LIST';
export const GET_VENUE_LIST_ERROR = 'GET_PLAYER_LIST_ERROR';
export const CREATE_VENUE = 'CREATE_PLAYER';
export const CREATE_VENUE_ERROR = 'CREATE_PLAYER_ERROR';
export const ACTION_ERROR = 'ACTION_ERROR';
