export const ACTION_START = 'ACTION_START';
export const ACTION_ERROR = 'ACTION_ERROR';
export const ACTION_COMPLETED = 'ACTION_COMPLETED';
export const FETCH_PLAYER_STATS = 'FETCH_PLAYER_STATS';
export const CLEAR_PLAYER_STATS = 'CLEAR_PLAYER_STATS';
export const FETCH_USER_STATS = 'FETCH_USER_STATS';
export const FETCH_MATCH_STATS = 'FETCH_MATCH_STATS';
