export const ACTION_START = 'ACTION_START';
export const ACTION_COMPLETED = 'ACTION_COMPLETED';
export const GET_TOURNAMENT_LIST = 'GET_TOURNAMENT_LIST';
export const GET_TOURNAMENT_LIST_ERROR = 'GET_TOURNAMENT_LIST_ERROR';
export const CREATE_TOURNAMENT = 'CREATE_TOURNAMENT';
export const CREATE_TOURNAMENT_ERROR = 'CREATE_TOURNAMENT_ERROR';
export const ACTION_ERROR = 'ACTION_ERROR';
