export const ACTION_START = 'ACTION_START';
export const ACTION_COMPLETED = 'ACTION_COMPLETED';
export const GET_TEAM_LIST = 'GET_TEAM_LIST';
export const GET_TEAM_LIST_ERROR = 'GET_TEAM_LIST_ERROR';
export const CREATE_SPORT_TEAM = 'CREATE_SPORT_TEAM';
export const CREATE_SPORT_TEAM_ERROR = 'CREATE_TOURNAMENT_ERROR';
export const ACTION_ERROR = 'ACTION_ERROR';
