export const ACTION_START = 'ACTION_START';
export const ACTION_COMPLETED = 'ACTION_COMPLETED';
export const GET_PLAYER_LIST = 'GET_PLAYER_LIST';
export const GET_PLAYER_LIST_ERROR = 'GET_PLAYER_LIST_ERROR';
export const CREATE_PLAYER = 'CREATE_PLAYER';
export const CREATE_PLAYER_ERROR = 'CREATE_PLAYER_ERROR';
export const ACTION_ERROR = 'ACTION_ERROR';
