export const ACTION_START = 'ACTION_START';
export const ACTION_ERROR = 'ACTION_ERROR';
export const ACTION_COMPLETED = 'ACTION_COMPLETED';
export const FETCH_LIVE_MATCHES_LIST = 'FETCH_LIVE_MATCHES_LIST';
export const FETCH_PLAYER_SCORE_BY_LIVE_MATCHES =
  'FETCH_PLAYER_SCORE_BY_LIVE_MATCHES';
export const FETCH_USER_TEAM_FOR_LIVE_MATCH = 'FETCH_USER_TEAM_FOR_LIVE_MATCH';
export const CLEAR_PLAYER_STATS = 'CLEAR_PLAYER_STATS';
