export const ACTION_START = 'ACTION_START';
export const ACTION_ERROR = 'ACTION_ERROR';
export const ACTION_COMPLETED = 'ACTION_COMPLETED';
export const FETCH_LIVE_MATCHES_LIST = 'FETCH_LIVE_MATCHES_LIST';
export const CLEAR_PLAYER_STATS = 'CLEAR_PLAYER_STATS';
