export const ACTION_START = 'ACTION_START';
export const ACTION_COMPLETED = 'ACTION_COMPLETED';
export const ACTION_ERROR = 'ACTION_ERROR';
export const GET_PUBLIC_LEAGUE_LIST = 'GET_PUBLIC_LEAGUE_LIST';
export const GET_LEAGUE_USER_RANKING = 'GET_LEAGUE_USER_RANKING';
export const JOIN_LEAGUE = 'JOIN_LEAGUE';
export const JOIN_LEAGUE_ERROR = 'JOIN_LEAGUE_ERROR';
export const GET_USER_LEAGUE = 'GET_USER_LEAGUE';
