export const ACTION_START = 'ACTION_START';
export const ACTION_COMPLETED = 'ACTION_COMPLETED';
export const ACTION_ERROR = 'ACTION_ERROR';
export const GET_PUBLIC_LEAGUE_LIST = 'GET_PUBLIC_LEAGUE_LIST';
export const GET_USER_LEAGUE = 'GET_USER_LEAGUE';
export const FETCH_ALL_PLAYER_LIST = 'FETCH_ALL_PLAYER_LIST';
export const FETCH_ALL_PLAYER_LIST_ERROR = 'FETCH_ALL_PLAYER_LIST_ERROR';
export const FETCH_PLAYER_LIST_BY_USER = 'FETCH_PLAYER_LIST_BY_USER';
export const FETCH_PLAYER_LIST_BY_USER_ERROR =
  'FETCH_PLAYER_LIST_BY_USER_ERROR';
export const UPDATE_INTERNAL_USER_TEAM = 'UPDATE_INTERNAL_USER_TEAM';
export const FETCH_USER_TEAM = 'FETCH_USER_TEAM';
export const FETCH_USER_TEAM_ERROR = 'FETCH_USER_TEAM_ERROR';
